services:
  meu-banco-postgres: # 2 espaços de recuo
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=banco_fhir
      - POSTGRES_USER=usuario_fhir
      - POSTGRES_PASSWORD=senha_secreta
    ports:
      - "5433:5432"
    volumes:
      - postgres_dados:/var/lib/postgresql/data

  meu-servidor-hapi: # 2 espaços de recuo (IGUAL ao banco acima)
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://meu-banco-postgres:5432/banco_fhir
      - spring.datasource.username=usuario_fhir
      - spring.datasource.password=senha_secreta
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.profiles.active=postgres
    depends_on:
      - meu-banco-postgres

volumes:
  postgres_dados: